Repository rust-embedded/showcase, pull requests merged in 2019-03, with the labels that each got.

#11 note that this is for applications, not libraries
  EVAL.md
  README.md
Labels: S-waiting-on-review, T-resources

#8 Add rusty clock
  data.yml
Labels: S-waiting-on-bors, T-resources

#13 Remove the dummy entries
  data.yml
Labels: S-waiting-on-bors, T-resources

#12 [RFC] rotate the list of projects on a daily basis
  Cargo.toml
  src/main.rs
Labels: T-resources

#14 Correct link to the resources team in the README.md
  README.md
Labels: S-waiting-on-review, T-resources

#15 Create CNAME file
  CNAME
Labels: S-waiting-on-review, T-resources
